### ISSUE TITLE
ERR symbols is not iterable: TypeError: symbols is not iterable

### ISSUE THREAD

**Issue by Nicolab** [crystal-lang-tools/vscode-crystal-lang#104]
Hello,

This extension doesn't work for me. 
There are several errors In the dev tools of VS code:

```
ERR symbols is not iterable: TypeError: symbols is not iterable
	at CrystalHoverProvider.<anonymous> (/home/nico/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalHover.js:85:44)
	at Generator.next (<anonymous>)
	at fulfilled (/home/nico/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalHover.js:4:58)
2
log.ts:196   ERR symbols is not iterable: TypeError: symbols is not iterable
	at CrystalCompletionItemProvider.<anonymous> (/home/nico/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalCompletion.js:250:36)
	at Generator.next (<anonymous>)
	at fulfilled (/home/nico/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalCompletion.js:4:58)
log.ts:196   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
	at CrystalCompletionItemProvider.<anonymous> (/home/nico/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalCompletion.js:108:48)
	at Generator.next (<anonymous>)
	at fulfilled (/home/nico/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalCompletion.js:4:58)

```

My config:

```json
"crystal-lang.completion": true,
    "crystal-lang.hover": true,
    "crystal-lang.implementations": true,
    "crystal-lang.compiler": "/usr/bin/crystal",
    "crystal-lang.shards": "/usr/bin/crystal.shards",
    // "crystal-lang.mainFile": "${workspaceRoot}/src/main.cr",
    "crystal-lang.processesLimit": 5
```

Ubuntu 18.04

VScode:

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-37-generic
```

Any idea?

**Comment by Nicolab** [comment]
I have installed https://github.com/crystal-lang-tools/scry, it works now.

Maybe it should be mentioned in the README
