### ISSUE TITLE
Crystal compiler not found. Some features can throw errors.

### ISSUE THREAD

**Issue by 73616c74** [crystal-lang-tools/vscode-crystal-lang#86]
## Description
I tested all possible paths (e.g. default, which, brew, #33).
But still shows that the compiler path was not found.
I tested some crystal versions (e.g. 0.27.0, 0.27.1, 0.27.2).
Crystal compiler not found related issues: #19 #33 #62 #63.

## Already Tested

* Default
```text
Just the default.
```

```json
{
	"crystal-lang.compiler": "crystal"
}
```

* Which
```text
iMac:~ User$ which crystal
/usr/local/bin/crystal
```

```json
{
	"crystal-lang.compiler": "/usr/local/bin/crystal"
}
```

* HomeBrew
```text
/usr/local/Cellar/crystal/0.27.2 (957 files, 50.3MB) *
  Poured from bottle on 2019-02-08 at 01:13:58
```

```json
{
	"crystal-lang.compiler": "/usr/local/Cellar/crystal/0.27.2/bin/crystal"
}
```

* Issue

```text
faustinoaq #33
```

```json
{
	"crystal-lang.compiler": "/usr/local/Cellar/crystal/0.27.2/src/compiler/crystal"
}
```

## Version Info
```text
Vs Code:
  Version 1.30.2 (1.30.2)
  61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
  2019-01-07T22:42:11.005Z

Crystal:
  Crystal 0.27.2 (2019-02-05)
  LLVM: 6.0.1
  Default target: x86_64-apple-macosx

macOS:
  macOS 10.12.6 (16G29)

Marketplace:
  This Plugin: 0.3.14
```

## Crystal Environment
```text
iMac:compiler User$ crystal env
CRYSTAL_CACHE_DIR="/Users/User/.cache/crystal"
CRYSTAL_PATH="/usr/local/Cellar/crystal/0.27.2/src:lib"
CRYSTAL_VERSION="0.27.2"
```

## HomeBrew Info
```
crystal: stable 0.27.2 (bottled), HEAD
Fast and statically typed, compiled language with Ruby-like syntax
https://crystal-lang.org/
/usr/local/Cellar/crystal/0.27.2 (957 files, 50.3MB) *
  Poured from bottle on 2019-02-08 at 01:13:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/crystal.rb
==> Dependencies
Build: libatomic_ops ✔
Required: bdw-gc ✔, gmp ✔, libevent ✔, libyaml ✔, llvm@6 ✔, pcre ✔, pkg-config ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

## Console Log
```text
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] Error: Command failed: crystal env
	at checkExecSyncError (child_process.js:613:13)
	at Object.execSync (child_process.js:653:13)
	at Object.execSync (ELECTRON_ASAR.js:721:23)
	at STDLIB (/Users/User/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalUtils.js:32:38)
	at Object.<anonymous> (/Users/User/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalUtils.js:44:3)
	at Object.<anonymous> (/Users/User/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalUtils.js:333:3)
	at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:963)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:767:268)
	at Function.t.getExtensionPathIndex.then.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:538)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:692:883)
	at Module.require (module.js:586:17)
	at n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:738)
	at Object.<anonymous> (/Users/User/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalMain.js:14:24)
	at Object.<anonymous> (/Users/User/.vscode/extensions/faustinoaq.crystal-lang-0.3.14/out/src/crystalMain.js:78:3)
	at Module.t._initNodeRequire.r._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:15:963)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:767:268)
	at Function.t.getExtensionPathIndex.then.s._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:749:538)
	at Function.t.getExtensionPathIndex.then.r._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:692:883)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.i [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:31:146)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:757:987
	at t._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:758:80)
	at t._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:756:785)
	at Object.actualActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:754:119)
	at e._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:344:190)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:343:782
	at Array.map (<anonymous>)
	at e._activateExtensions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:343:757)
	at e.activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:342:14)
	at t._activateByEvent (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:755:255)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:763:584
	at <anonymous>
```

## Screenshot

**Comment by faustinoaq** [comment]
Hi @73616c74 Thank you for report this issue!

> [Extension Host] Error: Command failed: crystal env

I think something is wrong with this:

https://github.com/crystal-lang-tools/vscode-crystal-lang/blob/69a19b3f313ea2db7e7edf1fca9c3f27737bad36/src/crystalUtils.ts#L38-L40

Let me try to fix it! :+1:

**Comment by faustinoaq** [comment]
@73616c74 Please try this:


[crystal-lang-0.3.15.pre-alpha.zip](https://github.com/crystal-lang-tools/vscode-crystal-lang/files/2847881/crystal-lang-0.3.15.pre-alpha.zip)

```
wget https://github.com/crystal-lang-tools/vscode-crystal-lang/files/2847881/crystal-lang-0.3.15.pre-alpha.zip
mv crystal-lang-0.3.15.pre-alpha.zip crystal-lang-0.3.15.pre-alpha.vsix
code --install-extension crystal-lang-0.3.15.pre-alpha.vsix
```

I changed `execSync` by `spawn`, please try this :point_up: and let me know if the error is still there.

Tested on WSL and Linux

**Comment by 73616c74** [comment]
@faustinoaq Thanks, Now it won't go wrong, 
But the plugin feature does not work.
<img width="319" alt="2019-02-09 22 40 13" src="https://user-images.githubusercontent.com/46258870/52522107-d2e15500-2cbb-11e9-884e-a4476fa7b783.png">

**Comment by 73616c74** [comment]
<img width="1440" alt="2019-02-09 22 44 42" src="https://user-images.githubusercontent.com/46258870/52522155-5ac75f00-2cbc-11e9-8c25-7a2e8996611f.png">

**Comment by faustinoaq** [comment]
> In addition, there is no log information in the console now.

Ok, Can you share your `settings.json`?

**Comment by faustinoaq** [comment]
Is `Format Document` available in your context menu?

**Comment by 73616c74** [comment]
---
> Ok, Can you share your `settings.json`?
---
```json
{
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "comment",
                    "comment.block",
                    "comment.block.documentation",
                    "comment.line",
                    "constant",
                    "constant.character",
                    "constant.character.escape",
                    "constant.numeric",
                    "constant.numeric.integer",
                    "constant.numeric.float",
                    "constant.numeric.hex",
                    "constant.numeric.octal",
                    "constant.other",
                    "constant.regexp",
                    "constant.rgb-value",
                    "emphasis",
                    "entity",
                    "entity.name",
                    "entity.name.class",
                    "entity.name.function",
                    "entity.name.method",
                    "entity.name.section",
                    "entity.name.selector",
                    "entity.name.tag",
                    "entity.name.type",
                    "entity.other",
                    "entity.other.attribute-name",
                    "entity.other.inherited-class",
                    "invalid",
                    "invalid.deprecated",
                    "invalid.illegal",
                    "keyword",
                    "keyword.control",
                    "keyword.operator",
                    "keyword.operator.new",
                    "keyword.operator.assignment",
                    "keyword.operator.arithmetic",
                    "keyword.operator.logical",
                    "keyword.other",
                    "markup",
                    "markup.bold",
                    "markup.changed",
                    "markup.deleted",
                    "markup.heading",
                    "markup.inline.raw",
                    "markup.inserted",
                    "markup.italic",
                    "markup.list",
                    "markup.list.numbered",
                    "markup.list.unnumbered",
                    "markup.other",
                    "markup.quote",
                    "markup.raw",
                    "markup.underline",
                    "markup.underline.link",
                    "meta",
                    "meta.block",
                    "meta.cast",
                    "meta.class",
                    "meta.function",
                    "meta.function-call",
                    "meta.preprocessor",
                    "meta.return-type",
                    "meta.selector",
                    "meta.tag",
                    "meta.type.annotation",
                    "meta.type",
                    "punctuation.definition.string.begin",
                    "punctuation.definition.string.end",
                    "punctuation.separator",
                    "punctuation.separator.continuation",
                    "punctuation.terminator",
                    "storage",
                    "storage.modifier",
                    "storage.type",
                    "string",
                    "string.interpolated",
                    "string.other",
                    "string.quoted",
                    "string.quoted.double",
                    "string.quoted.other",
                    "string.quoted.single",
                    "string.quoted.triple",
                    "string.regexp",
                    "string.unquoted",
                    "strong",
                    "support",
                    "support.class",
                    "support.constant",
                    "support.function",
                    "support.other",
                    "support.type",
                    "support.type.property-name",
                    "support.variable",
                    "variable",
                    "variable.language",
                    "variable.name",
                    "variable.other",
                    "variable.other.readwrite",
                    "variable.parameter"
                ],
                "settings": {
                    "fontStyle": ""
                }
            }
        ]
    },
    "editor.fontFamily": "PT Mono",
    "editor.fontSize": 14,
    "editor.formatOnPaste": true,
    "editor.multiCursorModifier": "ctrlCmd",
    "editor.snippetSuggestions": "top",
    "workbench.colorTheme": "Monokai",
    "workbench.sideBar.location": "right",
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "file-icons",
    "editor.fontWeight": "bold",
}
```
---
> Is `Format Document` available in your context menu?
---

* Yes, it exists

---

**Comment by 73616c74** [comment]
@faustinoaq Click on Format Document and a tilde prompt will appear.

**Comment by faustinoaq** [comment]
> Click on Format Document and a tilde prompt will appear.

What do you mean by tilde prompt?, Do you have a screencapture? :sweat_smile: 

Mine looks like this:

![image](https://user-images.githubusercontent.com/3067335/52524035-51130c80-2c66-11e9-808d-da58041e45d3.png)

Also try to add this to your settings.json:

```
{
    "crystal-lang.compiler": "/usr/local/bin/crystal",
    "crystal-lang.completion": true,
    "crystal-lang.hover": true,
    "crystal-lang.implementations": true
}
```

Please be aware most of them are experimental, see https://github.com/crystal-lang-tools/vscode-crystal-lang/wiki/Settings to get some info about them :sweat_smile: 

I'm currently working on migrate this whole VScode extension to use Scry by default, see: https://github.com/crystal-lang-tools/scry/

**Comment by 73616c74** [comment]
tilde prompt => Just like your screenshot.
@faustinoaq Thanks, After adding your configuration, 
Some features are starting to work,
But syntax errors are not automatically detected 
(Need to manually click on Format Document)

**Comment by faustinoaq** [comment]
> Is there any solution?

Yeah, two ways:

Easy one. You need to enable auto save, format on save, and format on type:

```
{
    "editor.formatOnType": true,
    "editor.formatOnSave": true,
    "files.autoSave": "afterDelay"
}
```

Advanced one. Try [Scry](https://github.com/crystal-lang-tools/scry/), it supports errors ontype and other cool experimental stuff:

```
cd /home/user/Projects
git clone https://github.com/crystal-lang-tools/scry.git
cd scry
shards build -v
```

Then setup scry on VSCode:

```
{
  "crystal-lang.server": "/home/user/Projects/scry/bin/scry",
}
```

![image](https://user-images.githubusercontent.com/3067335/52524491-82420b80-2c6b-11e9-9277-994c0ad54f05.png)


BTW, Looking deep into this issue I just found more pitfalls in this extension codebase :sweat_smile: I guess Scry can solve it as well :wink:

**Comment by 73616c74** [comment]
---
> BTW, Looking deep into this issue I just found more pitfalls in this extension codebase 😅 I guess Scry can solve it as well 😉
* 👍
---
> Advanced one. Try [Scry](https://github.com/crystal-lang-tools/scry/), it supports errors ontype and other cool experimental stuff:
* Perfect solution, thank you! 🙏
---

**Comment by faustinoaq** [comment]
> Looking deep into this issue I just found more pitfalls in this extension codebase 

Yep, `STDLIB` directory is not being detected at all, so, most Node.js based features don't gonna work.

Seems many things have changed on latest vscode API :sweat_smile: 

> Perfect solution, thank you! ￼

Yeah, looks like scry is the way to go :100:
